In [1]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

In [2]:
X = np.array([-8.0,-3.0,0.0,6.5,9.0,45.5])
X = X.reshape(-1,1)
k_means = KMeans(n_clusters=2)
k_means.fit(X)
centers = k_means.cluster_centers_
centers

array([[ 0.9],
       [45.5]])

GMM Algorithm

In [3]:
X = np.array([-8.0,-3.0,0.0,6.5,9.0,45.5])
X = X.reshape(-1,1)

In [4]:
from sklearn.mixture import GaussianMixture

In [5]:
gmm = GaussianMixture(n_components=2).fit(X)
labels = gmm.predict(X)

In [6]:
labels

array([0, 0, 0, 0, 0, 1])

In [27]:
X = np.array([-1.5,-1.0,-0.5,1.5,2.0,2.5])
X = X.reshape(-1,1)

In [28]:
gmm = GaussianMixture(n_components=2).fit(X)
labels = gmm.predict(X)

In [29]:
labels

array([0, 0, 0, 1, 1, 1])

In [31]:
gmm.predict_proba(X)

array([[1.00000000e+00, 2.32003973e-16],
       [1.00000000e+00, 1.87984295e-12],
       [9.99999985e-01, 1.52316764e-08],
       [1.52316764e-08, 9.99999985e-01],
       [1.87984295e-12, 1.00000000e+00],
       [2.32003973e-16, 1.00000000e+00]])

In [11]:
X_slim = X[3:]

In [12]:
np.var(X_slim)

0.16666666666666666

The responsibility of x=−0.5  for component 1, is given by (correct to four decimal places):	

In [13]:
X = np.array([-1.5,-1.0,-0.5,1.5,2.0,2.5])
X = X.reshape(-1,1)
k_means = KMeans(n_clusters=2)
k_means.fit(X)
centers = k_means.cluster_centers_
centers

array([[ 2.],
       [-1.]])

In [14]:
X = np.array([-1.5,-1.0,-0.5,1.5,2.0,2.5])
X = X.reshape(-1,1)
gmm = GaussianMixture(n_components=2).fit(X)
labels = gmm.predict(X)
labels
X_slim = X[:3]
np.var(X_slim)

0.16666666666666666

In [26]:
X = np.array([-1.5,-1.0,-0.5,1.5,2.0,2.5])
X = X.reshape(-1,1)
k_means = KMeans(n_clusters=2).fit(X)
labels = k_means.predict(X)
X_slim = X[:3]
np.mean(X_slim)

-1.0

In [16]:
labels

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [25]:
X_slim

array([[1.5],
       [2. ],
       [2.5]])

In [19]:
k_means.cluster_centers_

array([[ 2.],
       [-1.]])