In [47]:
import numpy as np

In [48]:
cov_mat = np.array([[2,1],[1,2]])

In [49]:
print('NumPy covariance matrix: \n%s' %cov_mat)

NumPy covariance matrix: 
[[2 1]
 [1 2]]


In [50]:
ei_vals, ev_vecs = np.linalg.eig(cov_mat)

In [51]:
print('ei_vals matrix: \n%s' %ei_vals)
print('ev_vecs matrix: \n%s' %ev_vecs)

ei_vals matrix: 
[3. 1.]
ev_vecs matrix: 
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [68]:
print('first pc1: \n%s' %ev_vecs[1])

first pc1: 
[0.70710678 0.70710678]


In [66]:
print('pc2: \n%s' %ev_vecs[0])

pc2: 
[ 0.70710678 -0.70710678]


In [64]:
print('smallest eigenvalue: \n%s' %ei_vals[1])

smallest eigenvalue: 
1.0


The angle between 2 vectors

In [67]:
vector_1 = [-111]
vector_2 = [-222]

unit_vector_1 = vector_1 / np.linalg.norm(vector_1)
unit_vector_2 = vector_2 / np.linalg.norm(vector_2)
dot_product = np.dot(unit_vector_1, unit_vector_2)
angle = np.arccos(dot_product)
angle/np.pi * 180

0.0

In [29]:
array_1 = [-111, np.nan]
array_2 = [-1, -11]

weight_1 = 0.5
weight_2 = 0.5

np.average(np.vstack((array_1, array_2)), axis=0, weights=[weight_1, weight_2])

array([-56.,  nan])

Length of vector:

In [65]:
a = [1,-1,2]

np.linalg.norm(a)

2.449489742783178

Product between 2 vectors

In [59]:
a = np.array([[0],[1]])
b = np.array([1,1])

np.dot(a,b)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

This should give the projection of vector x onto vector y - see

In [46]:
x = [-111]
y = [0 - 11]

np.dot(x, y) / np.linalg.norm(y)

111.0

# Quiz M3

In [73]:
a = [1,-1]
b = [[0],[1]]

np.dot(a,b)

array([-1])